### PR TITLE
Adding instructions page

### LINKED ISSUE #3: Create Nice Instructions Page
I suggest using the styles from the main CircuitVerse page. 
@aayush-05 @nitin10s any CSS assets that can quickly be copied to get started?

### PR DESCRIPTION
**Pull request by aryanbaburajan**
Fixes #3 

Please let me know your suggestions for the page, thanks!

Current screenshot:

image

### CODE REVIEW

**Comment by satu0king** [comment]
Looks nice! Please go ahead and write instructions

**Comment by aryanbaburajan** [comment]
I am yet to make the instructions page responsive, so i'll do it in the next commit!

**Comment by satu0king** [comment]
> I am yet to make the instructions page responsive, so i'll do it in the next commit!

Not required, cannot install this on a mobile browser anyway.

**Comment by satu0king** [comment]
@aryanbaburajan what is the purpose of the nav bar? we just need a simple neat instruction page saying congrats you installed the chrome extension. Now install the google slides add on from here etc.

**Comment by satu0king** [comment]
@AnandBaburajan I wanted to publish the extension, so I went forward without the instructions page but please continue working on it, we can add it to the next version.

**Comment by aryanbaburajan** [comment]
@satu0king Yep, I'm working on it. Also, @AnandBaburajan is my brother :)

**Comment by satu0king** [comment]
> @satu0king Yep, I'm working on it. Also, @AnandBaburajan is my brother :)

Lol okay, both have contributed here so I got confused lol

**Comment by anandbaburajan** [comment]
> Lol okay, both have contributed here so I got confused lol

I didn't contribute, but Aryan accidentally pushed a commit using my `git` 'commit email address', haha

**Comment by aryanbaburajan** [comment]
@satu0king I've finished the page, please let me know any suggestions!

Edit : Oops, the instructions page is done, but there's a problem with the Manifest file. I'll look into it and will fix it soon.

**Comment by aryanbaburajan** [comment]
@satu0king The page has been finished! Please take a look, thanks!

**Pull request closed without merging**
